### ISSUE TITLE
BlogPost.js

### ISSUE THREAD

**Issue by ldco2016** [ButterCMS/react-serverless-blog#1]
Greetings Roger,

How is this project coming along? Is this complete? I see the last time you worked on it was 7 months ago.

**Comment by jakelumetta** [comment]
Hey @ldco2016  - thanks for the note. Yes this project is complete. It's purpose was to serve as a simple example of using ButterCMS with React for a Serverless blog. You can take this repo and use it as a base to get started with your own blog. 

Did you have any questions?
